### ISSUE TITLE
TypeError: FitDataError.__init__() missing 2 required positional arguments: 'lower' and 'upper'

### ISSUE THREAD

**Issue by MrOlm** [MaayanLab/blitzgsea#14]
Hello,

Thanks again for creating such a useful tool!

I'm getting an odd multiprocessing error with `blitzgsea==1.3.27`. Attached is test data to reproduce the error. The first 2 work (tdb1 and tdb2), but it always crashes with an odd error with tdb3.

Best,
Matt

[gsea_files.zip](https://github.com/MaayanLab/blitzgsea/files/11446399/gsea_files.zip)

```
loc = '/home/mattolm/user_data/scratch/gsea_files/'

import blitzgsea as blitz
import pandas as pd

tdb1 = pd.read_pickle(loc + 'GUT_GENOME014039.fna.tdb.pickle')
tdb2 = pd.read_pickle(loc + 'GUT_GENOME042029.fna.tdb.pickle')
tdb3 = pd.read_pickle(loc + 'METABAT215_SUBJECTMAPPING_SCAFFOLDS_1500_ASSEMBLY_K77_MERGED__Pilot_MoBio_Fiber_A_5_1019.165.fa.tdb.pickle')
k2p = pd.read_pickle(loc + 'k2p.pickle')

rdb1 = blitz.gsea(tdb1, k2p, seed=1)
rdb2 = blitz.gsea(tdb2, k2p, seed=1)
rdb3 = blitz.gsea(tdb3, k2p, seed=1)

Exception in thread Thread-30 (_handle_results):
Traceback (most recent call last):
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: FitDataError.__init__() missing 2 required positional arguments: 'lower' and 'upper'
```

**Comment by lachmann12** [comment]
i did update some of the code. Maybe the issue is resolved with this, but it is not clear to me at the moment what causes this error message. Could you try the latest version and see if the issue is still there?

**Comment by MrOlm** [comment]
That worked! Thank you again
